services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - CORS_ORIGINS=http://localhost:3000
      - HOST_EXOMINER_PATH=C:/Users/lucho/Documents/project/exoplanet-hunter/backend/exominer_work  # Chemin sur l'hôte pour ExoMiner
    volumes:
      - ./backend:/app
      - ./data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock  # Accès au Docker de l'hôte
      - ./backend/exominer_work:/app/exominer_work  # Persister les jobs ExoMiner
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    privileged: true  # Nécessaire pour exécuter Docker depuis Docker

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
