bash run_podman_application.sh \
  --tics_tbl_fp "$HOME/exominer/inputs/tics_tbl.csv" \
  --exominer_pipeline_run_dir "$HOME/exominer/runs/test_run_001" \
  --data_collection_mode "2min" \
  --num_processes 4 \
  --num_jobs 2 \
  --download_spoc_data_products "true" \
  --external_data_repository "null" \
  --stellar_parameters_source "ticv8" \
  --ruwe_source "gaiadr2" \
  --exominer_model "exominer++_single"
